/* automatically generated by rust-bindgen */

use libc::*;
#[link(name = "jinja2")]
extern "C" {
    pub fn init_environment(arg1: *c_char) -> *mut c_void;
    pub fn render(arg1: *mut c_void, arg2: c_int, arg3: *mut *mut c_char) ->
     *mut c_char;
    pub fn free_environment(arg1: *mut c_void);
    pub fn get_template(arg1: *mut c_void, arg2: *c_char) -> *mut c_void;
    pub fn list_templates(env: *mut c_void);
}
